### ISSUE TITLE
How to reload config?

### ISSUE THREAD

**Issue by mustardfrog** [Walker-00/sswm#1]
Do i have to recompile the project to apply new changes from config?

**Comment by Walker-00** [comment]
@mustardfrog nah you don't have to recompile the pj again. for now refreshing is still not supported, but you can kill and restart the wm, it will auto detect it. thanks for your first issue open.

**Comment by mustardfrog** [comment]
This is really exciting. And now i want learn more about windows managers. 

Are you working on this project alone?  If so, I will try to contribute to it.

btw I made a facebook group called "Myanmar Rustaceans" and you are welcome to join. (it has me and my two other friends who don't even know programming haha)

**Comment by Walker-00** [comment]
Yep I'm working alone, and I'm happy to welcome you or others contributions and feedback as 15 y.o drop out open source programmer, it mean a lot.

**Comment by mustardfrog** [comment]
I am no master either. I just wanna learn rust and this may be the perfect spot.

**Comment by Walker-00** [comment]
Joined the group.

**Comment by mustardfrog** [comment]
Nice
