### ISSUE TITLE
Error on compiling 

### ISSUE THREAD

**Issue by RizeKishimaro** [Walker-00/sswm#4]
OS: Ubuntu 20.04LTS

cargo-src: from package managers

DE: no

WM: yes(I3wm)

try to compile on i3wm but it's an error while compiling.

TERMINAL LOGS::

error: failed to run custom build command for `libseat-sys v0.1.7`

Caused by:
  process didn't exit successfully: `/home/woody/Desktop/nestProjects/task-scheduling/sswm/target/release/build/libseat-sys-766419febbf22492/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBSEAT_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBSEAT_STATIC
  cargo:rerun-if-env-changed=LIBSEAT_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: `"pkg-config" "--libs" "--cflags" "libseat"` did not exit successfully: exit status: 1
  error: could not find system library 'libseat' required by the 'libseat-sys' crate

  --- stderr
  Package libseat was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libseat.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'libseat', required by 'virtual:world', not found
  ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libseat-sys-0.1.7/build.rs:30:42
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sswm v0.0.1 (/home/woody/Desktop/nestProjects/task-scheduling/sswm)`, intermediate artifacts can be found at `/home/woody/Desktop/nestProjects/task-scheduling/sswm/target`

screen shot?

![image](https://github.com/Walker-00/sswm/assets/75617768/bbdf53a4-698f-499c-b1b6-104fde66adbd)

**Comment by Walker-00** [comment]
You are too g@y to compile rust projects.

**Comment by Walker-00** [comment]
Jkd. install `libseat`. you can install it like ```sudo apt install libseat-dev``` in ubuntu I think.

**Comment by Walker-00** [comment]
RTFM bruh.

**Comment by Walker-00** [comment]
I'll close it :3

**Comment by RizeKishimaro** [comment]
> I'll close it :3

close it if you gay

**Comment by Walker-00** [comment]
> > I'll close it :3
> 
> close it if you gay

bruh you gay
